---
# This role contains common plays that will run on all nodes.

- name: Raw bootstrap for python
  action: apt pkg={{ item }} state=present update-cache=yes
  with_items:
    - python

- name: remove some useless packages
  action: apt pkg={{ item }} state=absent
  with_items:
  - puppet
  - chef

- name: set up authorized keys for demo boxes
  authorized_key: user=vagrant key="{{ lookup('file', 'id_rsa.pub') }}"
    manage_dir=yes state=present 

- name: fix permissions
  shell: sudo chown -R vagrant.vagrant /home/vagrant
